Product.create! cod: 'TCE100', name: 'TUBO PVC 100MM x 6M COLETOR ESGOTO', price: rand(1.3..6)
Product.create! cod: 'TCE150', name: 'TUBO PVC 150MM x 6M COLETOR ESGOTO', price: rand(1.3..6)
Product.create! cod: 'TCE75', name: 'TUBO PVC 75MM x 6M COLETOR ESGOTO', price: rand(1.3..6)
Product.create! cod: 'TCE50', name: 'TUBO PVC 50MM x 6M COLETOR ESGOTO', price: rand(1.3..6)
Product.create! cod: 'TCE40', name: 'TUBO PVC 40MM x 6M COLETOR ESGOTO', price: rand(1.3..6)
Product.create! cod: 'TE20', name: 'TUBO PVC 20MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TE25', name: 'TUBO PVC 25MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TE32', name: 'TUBO PVC 32MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TE40', name: 'TUBO PVC 40MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TE50', name: 'TUBO PVC 50MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TE60', name: 'TUBO PVC 60MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TE75', name: 'TUBO PVC 75MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TE85', name: 'TUBO PVC 85MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TE110', name: 'TUBO PVC 110MM x 3M ELETRODUTO', price: rand(1.3..6)
Product.create! cod: 'TS20', name: 'TUBO PVC 20MM x 6M SOLDAVEL', price: rand(1.3..6)
Product.create! cod: 'TS25', name: 'TUBO PVC 25MM x 6M SOLDAVEL', price: rand(1.3..6)
Product.create! cod: 'TS32', name: 'TUBO PVC 32MM x 6M SOLDAVEL', price: rand(1.3..6)
Product.create! cod: 'TS40', name: 'TUBO PVC 40MM x 6M SOLDAVEL', price: rand(1.3..6)
Product.create! cod: 'TS50', name: 'TUBO PVC 50MM x 6M SOLDAVEL', price: rand(1.3..6)
Product.create! cod: 'TS60', name: 'TUBO PVC 60MM x 6M SOLDAVEL', price: rand(1.3..6)
Product.create! cod: 'TS75', name: 'TUBO PVC 75MM x 6M SOLDAVEL', price: rand(1.3..6)
Product.create! cod: 'TS100', name: 'TUBO PVC 110MM x 6M SOLDAVEL PN 80', price: rand(1.3..6)
Product.create! cod: 'CE9020', name: 'CURVA ELETRODUTO 20MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE9025', name: 'CURVA ELETRODUTO 25MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE9032', name: 'CURVA ELETRODUTO 32MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE9040', name: 'CURVA ELETRODUTO 40MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE9050', name: 'CURVA ELETRODUTO 50MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE9060', name: 'CURVA ELETRODUTO 60MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE9075', name: 'CURVA ELETRODUTO 75MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE9085', name: 'CURVA ELETRODUTO 85MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE90110', name: 'CURVA ELETRODUTO 110MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE1820', name: 'CURVA ELETRODUTO 20MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE1825', name: 'CURVA ELETRODUTO 25MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE1832', name: 'CURVA ELETRODUTO 32MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE1840', name: 'CURVA ELETRODUTO 40MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE1850', name: 'CURVA ELETRODUTO 50MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE1860', name: 'CURVA ELETRODUTO 60MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE1875', name: 'CURVA ELETRODUTO 75MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'CE1885', name: 'CURVA ELETRODUTO 85MM PVC PB', price: rand(1.3..6)
Product.create! cod: 'BE1,5', name: 'BENGALA ELETRODUTO 25MM X 1,5M', price: rand(1.3..6)
Product.create! cod: 'BE3', name: 'BENGALA ELETRODUTO 25MM X 3M', price: rand(1.3..6)
Product.create! cod: 'MI1', name: 'MANGUEIRA DE IRRIGAÇÃO POTY MASTER DE "1"', price: rand(1.3..6)
Product.create! cod: 'MI3/4', name: 'MANGUEIRA DE IRRIGAÇÃO POTY MASTER DE 3⁄4', price: rand(1.3..6)
Product.create! cod: 'MI1/2', name: 'MANGUEIRA DE IRRIGAÇÃO POTY MASTER DE 1⁄2', price: rand(1.3..6)