:verbose: false
:concurrency: 2

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 15

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - jobs
  - mailers
  - <%= `hostname`.strip %>
  - low

# you can override concurrency based on environment
production:
  :concurrency: 5

:dynamic: false #<if true the schedule can be modified in runtime [false by default]>
:dynamic_every: true #<if dynamic is true, the schedule is reloaded every interval [5s by default]>
:enabled: true #<enables scheduler if true [true by default]>
:scheduler:
  :listened_queues_only: false #<push jobs whose queue is being listened by sidekiq [false by default]>

:schedule:
  FindBillPayableJob:
    description: "Atualiza status dos pagamentos"
    # cron: '0 */5 * * * *'   # Runs when second = 0, every 5 minutes
    cron: '0 00 00 * * *'   # Runs every hour
    # every: '24h'   # Runs every hour
    # queue: jobs
    # Enable / disable a job. All jobs are enabled by default.
    enabled: true

  FindBillReceivableJob:
    description: "Atualiza status dos recebimentos"
    # cron: '0 */5 * * * *'   # Runs when second = 0, every 5 minutes
    cron: '0 00 00 * * *'   # Runs every hour
    # every: '24h'   # Runs every hour
    # queue: jobs
    # Enable / disable a job. All jobs are enabled by default.
    enabled: true